"""empty message

Revision ID: 1a04ca7a7c70
Revises: 8d6d5c6f81cd
Create Date: 2024-06-15 19:15:29.769517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a04ca7a7c70'
down_revision: Union[str, None] = '8d6d5c6f81cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reviews', 'master_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reviews', 'master_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
