"""empty message

Revision ID: 2b9fc7dc8ae1
Revises: 3f24d9e74e6c
Create Date: 2024-06-10 15:36:53.930765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b9fc7dc8ae1'
down_revision: Union[str, None] = '3f24d9e74e6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
