"""empty message

Revision ID: 4ffe8eb0decc
Revises: f21dcc28da6d
Create Date: 2024-06-11 00:52:25.960914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ffe8eb0decc'
down_revision: Union[str, None] = 'f21dcc28da6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'ratings', ['salon_id'])
    op.create_unique_constraint(None, 'salons', ['rating_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'salons', type_='unique')
    op.drop_constraint(None, 'ratings', type_='unique')
    # ### end Alembic commands ###
