"""empty message

Revision ID: 53e0e75eabeb
Revises: 31750c273ea3
Create Date: 2024-06-12 12:20:09.273040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53e0e75eabeb'
down_revision: Union[str, None] = '31750c273ea3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('salons', 'rating_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('salons', 'rating_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
