"""empty message

Revision ID: 66329aa63e1e
Revises: 2b9fc7dc8ae1
Create Date: 2024-06-10 15:38:23.089547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66329aa63e1e'
down_revision: Union[str, None] = '2b9fc7dc8ae1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
