"""empty message

Revision ID: bb362991d2ed
Revises: 4ffe8eb0decc
Create Date: 2024-06-11 09:17:48.797674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb362991d2ed'
down_revision: Union[str, None] = '4ffe8eb0decc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ratings', 'rating',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_constraint('ratings_salon_id_key', 'ratings', type_='unique')
    op.drop_constraint('ratings_salon_id_fkey', 'ratings', type_='foreignkey')
    op.drop_column('ratings', 'salon_id')
    op.alter_column('salons', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('salons', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('salons', 'address',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('salons', 'phone_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('salons', 'rating_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('salons', 'review_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('salons_rating_id_key', 'salons', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('salons_rating_id_key', 'salons', ['rating_id'])
    op.alter_column('salons', 'review_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('salons', 'rating_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('salons', 'phone_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('salons', 'address',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('salons', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('salons', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('ratings', sa.Column('salon_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('ratings_salon_id_fkey', 'ratings', 'salons', ['salon_id'], ['id'])
    op.create_unique_constraint('ratings_salon_id_key', 'ratings', ['salon_id'])
    op.alter_column('ratings', 'rating',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    # ### end Alembic commands ###
