from dependencies.database.db import Base
from models.salon_model import Base
from models.salon_rating_model import Base
from models.user_model import Base
from models.review_model import Base
from models.appointment_model import Base
from models.master_model import Base
from models.master_rating_model import Base
from models.service_model import Base
from models.category_model import Base
from models.service_price_model import Base
